<?xml version="1.0"?>
<package format="3">
  <name>lidar_detection_ros</name>
  <version>0.1.0</version>
  <description>PointPillars inference for Unitree/Livox PointCloud2 topics.</description>
  <maintainer email="noreply@example.com">Aymeric Schaeffer</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>diagnostic_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>
  <exec_depend>python3-numpy</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
